modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/UntitledModGroup/better-biome-blend-reblend"
license = "LGPL"

[[mods]]
modId = "betterbiomereblend"
version = "${version}"
displayName = "Better Biome ReBlend"
authors = "FionaTheMortal"
description = "    This mod increases the biome color blending radius and replaces the original blending algorithm with a more efficient one."
#logoFile = ""

[[dependencies.betterbiomeblend]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterbiomeblend]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.0,)"
ordering = "NONE"
side = "BOTH"
