modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/UntitledModGroup/better-biome-blend-reblend/issues"
displayURL = "https://modrinth.com/mod/bbrb"
license = "GNU LGPLv3"

[[mixins]]
config = "betterbiomeblend-common.mixins.json"

[[mods]]
modId = "betterbiomeblend"
version = "${version}"
displayName = "Better Biome Reblend"
authors = "FionaTheMortal + UTMG"
logoFile = "icon.png"
description = '''
This mod increases the biome color blending radius and replaces the original blending algorithm with a more efficient one.
'''
#logofile = ""

[[dependencies.betterbiomeblend]]
modId="minecraft"
versionRange="[1.21,)"
ordering="NONE"
side = "CLIENT"

[[dependencies.betterbiomeblend]]
modId = "neoforge"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"